#!/usr/bin/bash

while :
do
    echo -e "\n"
	echo "---------------------------------------------------"
	echo "      Parser Of On-campus Preferred Specials       "
    echo "                      a.k.a.                       "
    echo "        ______ ______ ______ ______  _____         "
    echo "       |   _  |  __  |  __  |   _  |/ ____|        "
    echo "       |  |_) | |  | | |  | |  |_) | (___          "
    echo "       |   ___| |  | | |  | |   ___|\___ \         "
    echo "       |  |   | |__| | |__| |  |    ____) |        "
    echo "       |  |   |      |      |  |   |      |        "
    echo "       |__|   |______|______|__|   |_____/         "
    echo "                                                   "
    echo "      Choose one of the following restuarants      "
    echo "             to view today's specials              "
    echo "                                                   "
    echo "       Today is `date`                             "
	echo "---------------------------------------------------"
	echo "[1] Brick City Cafe"
	echo "[2] Commons"
	echo "[3] Crossroads"
	echo "[4] Global Village Cantina and Grille"
	echo "[5] Gracies"
    echo "[6] Ritz Sports Zone"
    echo "[q] Quit"
	echo "==================================================="
	echo -n "Enter your menu choice [1-6 or q]: "
	read yourchoice
	case $yourchoice in
		1) less /tmp/Poops/brickCityCafe.txt;;
		2) less /tmp/Poops/commons.txt;;
		3) less /tmp/Poops/crossRoads.txt;;
		4) less /tmp/Poops/globalVillage.txt;;
		5) less /tmp/Poops/gracies.txt;;
        6) less /tmp/Poops/ritz.txt;;
        q) exit 0 ;;
		*) echo "Oops! Please select choice 1,2,3,4,5,6 or q";
		   echo "Press the Enter key..." ; read ;;
esac
done
