#!/usr/bin/env python

""" POOPS.py
    python2.6
    Author: Sean Jones
    Description: My python web scraper that gets the daily dining specials of
                 restuarants on campus.
"""

from BeautifulSoup import BeautifulSoup, NavigableString
from sys import version, exit
import urllib2, time, unicodedata

if version.split()[0][0] == '3':
    print( "This won't run unless you are using python version 2.*" )
    exit()    

class Restaurant(object):
    __slots__ = ("link", "filename", "contents", "undesireables")

    def __init__(self, link, filename):
        self.link = link
        self.filename = filename
        self.contents = set()
        self.undesireables = set()
        lst = ["BUSINESS SERVICES", "Human Resources", "Digital Den",
               "Forms", "Napkin Dispenser/Table Tent Policy",
               "Legal Affairs", "Leadership Staff", "Resources",
               "All Day", "Information &amp; Technology Services",
               "RISK MANAGEMENT", "Bookstore",
               "Specialty Wraps-located at Deli", "Bottle Return",
               "Training", "Institute Audit, Compliance &amp; Advisement",
               "Weekly Menus", "Directories", "Facilities Management",
               "Parking &amp; Transportation", "Student Auxiliary Services",
               "Housing Operations", "Tiger Bucks Program",
               "Gordon Field House", "Hours", "Controller",
               "Senior Vice President", "Student Financial Services",
               "About Us/Contacts", "Budget", "Dining Services", "In The News",
               "Special Delivery", "Global Risk Management Services",
               "Print &amp; Postal Hub", "Public Safety", 
               "EMPLOYMENT SERVICES", "Center for Professional Development",
               "FINANCIAL SERVICES", "A-Z Index", "Nutrition",
               "Systems &amp; Technologies", "Hot Meals Under $6",
               "Information Security", "Career Zone", "Search", "Vending",
               "Procurement Services", "Ethics &amp; Compliance",
               "Institutional Research", "Gift Cards",
               "Meal Plans and Debit Plans", "Environmental Health &amp; Safety",
               "Locations", "Emergency Preparedness", "Business Continuity",
               "F&amp;A LEADERSHIP", "MyRIT", "F&amp;A Home", "Payroll",
               "Catering", "Tiger Bucks", "Student Employment",
               "RIT Inn &amp; Conference Center", "Publications", "Accounting",
               "Restaurant Vendors", "Gracies", "The Ritz Sports Zone",
               "Brick City Caf\xc3\xa9", "The Commons", "Choices", 
               "The Caf\xc3\xa9 &amp; Market at the Crossroads" ]
        for i in lst:
            self.undesireables.add(i)
               
    def printText(self, tags):
        File = open(self.filename,'w')
        for tag in tags:
            if isinstance(tag, NavigableString):
                string = str(tag)
                string = string.strip()
                if string != "":
                    if string not in self.undesireables:
                        self.contents.add(string.replace("&amp;","&"))
            else:
                self.printText(tag)
        for i in self.contents:
            print>>File, i.replace("*", "")     
        File.close()


    def parseText(self):
        File = open(self.filename,'r')
        for line in File:
            self.contents.append(line.split())
        File.close()

brickCityCafe = Restaurant("http://finweb.rit.edu/diningservices/brickcity",
                           "/tmp/Poops/brickCityCafe.txt")
commons = Restaurant("http://finweb.rit.edu/diningservices/commons",
                     "/tmp/Poops/commons.txt")
crossRoads = Restaurant("http://finweb.rit.edu/diningservices/crossroads",
                        "/tmp/Poops/crossRoads.txt")
globalVillage = Restaurant("http://finweb.rit.edu/diningservices/gvcantinagrille",
                           "/tmp/Poops/globalVillage.txt")
gracies = Restaurant("http://finweb.rit.edu/diningservices/gracies",
                     "/tmp/Poops/gracies.txt")
ritz = Restaurant("http://finweb.rit.edu/diningservices/ritzsportszone",
                  "/tmp/Poops/ritz.txt")

restaurants = [brickCityCafe, commons, crossRoads, globalVillage, gracies, ritz]

print time.ctime()

for restaurant in restaurants:
    #FILE = open(restaurant.filename, "w")
    html = urllib2.urlopen(restaurant.link).read()
    soup = BeautifulSoup(html)
    #print soup.findAll("li")
    restaurant.printText(soup.findAll("li"))
    print restaurant.contents
    #FILE.close()
    #restaurant.parseText()
    #print restaurant.filename, restaurant.contents[:]
    # First parse
    #FILE = open(restaurant.filename, "r")
    #temp = open("tmp.txt", "w")
print time.ctime()
